### ISSUE TITLE
Export for Kubernetes

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#960]
## Description

Related to #954

If the user wants to have both secrets and variables into the **Secrets** resource, then the output should look like this, where there would be just one file:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  API_KEY: YWJjZDEyMzQ=        # abcd1234
  GITHUB_TOKEN: Z2hwXzU2Nzg=  # ghp_5678
  PORT: MzAwMA==              # 3000
```

If the user wants it separately in config maps and secrets, the output should look like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  API_KEY: YWJjZDEyMzQ=         # abcd1234
  GITHUB_TOKEN: Z2hwXzU2Nzg=   # ghp_5678
```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  PORT: "3000"
```
